#dev settings - stubs for now
version: '3.3'
services:
  db:
    image: postgres
    volumes:
      - /mnt/data/postgresql/data:/var/lib/postgresql/data
    user: ${USER}:${USER}
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.group == db
  web:
    build: ./
    ports:
      - "8081:8081"
    environment:
      - RAILS_ENV=development
    volumes:
      - ./:/stereopaw
      # needed for .env.json config
      - /home/vergeman/Dropbox/stereopaw/:/home/vergeman/Dropbox/stereopaw/
    working_dir: /stereopaw/app
    command: ["entrypoint.sh", "rails", "server", "-b", "0.0.0.0", "-p", "8081"]
