#prod first
version: '3.3'
services:
  db:
    image: postgres
    volumes:
      - /mnt/data/postgresql/data:/var/lib/postgresql/data
    user: ${USER}:${USER}
    ports:
      - "5432:5432"
  web:
    build: ./
    image: "stereopaw/stereopaw:latest"
    env_file:
      - .env
    user: ${USER}:${USER}
    volumes:
      - ./:/stereopaw
      # change for marklet/extension .env location
      # needed for symlinked .env.json config
      - /home/vergeman/Dropbox/stereopaw/:/home/vergeman/Dropbox/stereopaw/
    working_dir: /stereopaw/app
    command: ["entrypoint.sh", "rails", "server", "-b", "0.0.0.0", "-p", "8081"]
    ports:
      - "8081:8081"
    depends_on:
      - db
