development:
    adapter: postgresql
    encoding: unicode
    database: soundbyte_dev
    username: alan
    pool: 5

test:
    adapter: postgresql
    encoding: unicode
    database: soundbyte_test
    username: alan
    pool: 5

production:
    adapter: postgresql
    encoding: unicode
    database: soundbyte_production
    username: alan
    pool: 5

