development:
    adapter: postgresql
    encoding: unicode
    database: soundbyte_dev
    host: <%= ENV['DEV_DB_HOST'] %>
    password: <%= ENV['DEV_DB_PASSWORD'] %>
    username: postgres
    pool: 5

test:
    adapter: postgresql
    encoding: unicode
    database: soundbyte_test
    host: <%= ENV['DEV_DB_HOST'] %>
    username: postgres
    pool: 5

staging:
    adapter: postgresql
    encoding: unicode
    database: soundbyte_production
    username: stereopaw
    host: <%= ENV['STAGING_DB_HOST'] %>
    password: <%= ENV['STAGING_DB_PASSWORD'] %>
    pool: 5

production:
    adapter: postgresql
    encoding: unicode
    database: soundbyte_production
    username: stereopaw
    host: <%= ENV['PRODUCTION_DB_HOST'] %>
    password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
    pool: 5
